---
formatter: markdown table

header-from: main.tf
content: |-
    # ☁️ Route 53 DNS records
    ## Description
    {{ .Header }}
    This module create DNS records of its allowed types in a Route 53 hosted zone. Its current capabilities are:
    * 🚀 Create DNS records of the following types:
        * A
        * AAAA
        * CNAME
        * MX
        * NS
        * PTR
        * SOA
        * SPF
        * SRV
        * TXT
    For more information about this resource, see [DNS Records (Resource Record Sets)](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/resource-record-sets-choosing-alias-non-alias.html) in the *Amazon Route 53 Developer Guide*.

    ---
    ## Example
    Examples of this module's usage are available in the [examples](./examples) folder.

    ```hcl
    {{ include "../../examples/route53-dns-records/basic/main.tf" }}
    ```
    ```hcl
    {{ include "../../examples/route53-dns-records/basic/config/fixtures.tfvars" }}
    ```
    ---

    ## Module's documentation
    (This documentation is auto-generated using [terraform-docs](https://terraform-docs.io))
    {{ .Providers }}

    {{ .Modules }}

    {{ .Resources }}

    {{ .Requirements }}

    {{ .Inputs }}

    {{ .Outputs }}

output:
    file: README.md
    mode: inject
    template: |-
        <!-- BEGIN_TF_DOCS -->
        {{ .Content }}
        <!-- END_TF_DOCS -->
settings:
    anchor: true
    color: true
