---
formatter: markdown table

header-from: main.tf
content: |-
    # ☁️ Route 53 Hosted Zone
    ## Description
    {{ .Header }}
    This module creates a Route 53 hosted zone
    * 🚀 Create a Route 53 hosted zone
    For more information about this resource, please refer to its official documentation in: [AWS Route 53](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/route53_zone)

    ---
    ## Example
    Examples of this module's usage are available in the [examples](./examples) folder.

    ```hcl
    {{ include "../../examples/route53-hosted-zone/basic/main.tf" }}
    ```
    ```hcl
    {{ include "../../examples/route53-hosted-zone/basic/config/fixtures.tfvars" }}
    ```

    Example of a configuration that also creates subdomains, with proper NS records.

    ```hcl
    {{ include "../../examples/route53-hosted-zone/basic/config/fixtures-with-subdomains.tfvars" }}
    ```

    ---

    ## Module's documentation
    (This documentation is auto-generated using [terraform-docs](https://terraform-docs.io))
    {{ .Providers }}

    {{ .Modules }}

    {{ .Resources }}

    {{ .Requirements }}

    {{ .Inputs }}

    {{ .Outputs }}

output:
    file: README.md
    mode: inject
    template: |-
        <!-- BEGIN_TF_DOCS -->
        {{ .Content }}
        <!-- END_TF_DOCS -->
settings:
    anchor: true
    color: true
